import fs from 'node:fs';
import assert from 'node:assert/strict';
const code = fs.readFileSync('modules/grimmes-erwachen/assets/rendered-v2/Import-Karten.js', 'utf8');
const AsyncFunction = Object.getPrototypeOf(async function() {}).constructor;
const run = new AsyncFunction('game','fetch','Folder','Scene','foundry','ui',code);
const existing = {name:'Bestehende Szene',getFlag:()=>undefined};
const game = {user:{isGM:true}, release:{generation:14}, folders:[], scenes:[existing]};
const record = {key:'test',name:'Testkarte',file:'karten/test.png',widthMeters:30,pixelWidth:1500,pixelHeight:1000};
const fetchOk = async()=>({ok:true,json:async()=>({maps:[record]})});
const Folder = {create: async d => {const f={...d,id:'folder1'};game.folders.push(f);return f;}};
const Scene = {create: async d=>{game.scenes.push({...d,getFlag:(scope,key)=>d.flags[scope]?.[key]});}};
const foundry = {utils:{randomID:()=> '1234567890abcdef'}};
const ui = {notifications:{info:()=>{}}};
await run(game,fetchOk,Folder,Scene,foundry,ui);
assert.equal(game.scenes.length,2);
assert.equal(game.scenes[0],existing);
assert.equal(game.scenes[1].grid.distance,1);
assert.equal(game.scenes[1].grid.size,100);
assert.equal(game.scenes[1].width,3000);
assert.equal(game.scenes[1].height,2000);
assert.equal(game.scenes[1].levels[0].background.src,'modules/grimmes-erwachen/assets/rendered-v2/karten/test.png');
assert.equal(game.scenes[1].initialLevel,game.scenes[1].levels[0]._id);
assert.equal(game.scenes[1].walls,undefined);
await run(game,fetchOk,Folder,Scene,foundry,ui);
assert.equal(game.scenes.length,2);
assert.equal(game.folders.length,1);
await assert.rejects(run(game,async(url,options)=>options?.method==='HEAD'?{ok:false}:fetchOk(),Folder,Scene,foundry,ui),/Hintergrund fehlt/);
assert.equal(game.scenes.length,2);
console.log('Import geprüft: 1-m-Raster, V14-Level, vorhandene Szenen erhalten, idempotent, fehlende Bilder stoppen vor Änderungen. Kein Live-Foundry-Test.');
